# Generated by Django 5.1.4 on 2025-01-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_question_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created']},
        ),
    ]
