# Generated by Django 5.1.4 on 2025-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_question_topic_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
