# Generated by Django 5.1.4 on 2025-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Tytuł pytania', max_length=120),
        ),
    ]
